-- Your SQL goes here
CREATE TABLE posts (
  id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  name VARCHAR NOT NULL,
  date DATE NOT NULL,
  message TEXT NOT NULL,
  published BOOLEAN NOT NULL DEFAULT 0,
  thumbnail VARCHAR REFERENCES thumbnails ON UPDATE CASCADE
)
