-- Your SQL goes here
CREATE TABLE posts (
  id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  name VARCHAR NOT NULL,
  date DATE NOT NULL,
  message TEXT NOT NULL,
  published BOOLEAN NOT NULL DEFAULT 0,
  thumbnail VARCHAR REFERENCES thumbnails ON UPDATE CASCADE
);

CREATE TABLE inquiries (
  id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  name VARCHAR NOT NULL,
  message TEXT NOT NULL,
  email TEXT NOT NULL,
  business BOOLEAN NOT NULL DEFAULT 0
);

CREATE TABLE comments (
  post_id INTEGER NOT NULL REFERENCES posts ON DELETE CASCADE ON UPDATE CASCADE,
  id INTEGER NOT NULL,
  name VARCHAR NOT NULL,
  date DATE NOT NULL,
  contents VARCHAR NOT NULL,
  PRIMARY KEY(id,post_id)
);

CREATE TABLE thumbnails (
  filepath VARCHAR PRIMARY KEY NOT NULL,
  alt_text VARCHAR
);
