-- Your SQL goes here



CREATE TABLE inquiries (
  id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  name VARCHAR NOT NULL,
  message TEXT NOT NULL,
  email TEXT NOT NULL,
  business BOOLEAN NOT NULL DEFAULT 0
)
